import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../features/triage/domain/entities/triage_entities.dart';
import '../../features/triage/presentation/triage_chat_controller.dart';

class PdfGenerator {
  static Future<void> generateAndShareReport(Assessment assessment, {List<TriageChatMessage>? chatHistory}) async {
    try {
      final pdf = pw.Document();
      
      pw.Font font;
      pw.Font boldFont;
      
      try {
        font = await PdfGoogleFonts.notoSansRegular();
        boldFont = await PdfGoogleFonts.notoSansBold();
      } catch (e) {
        font = pw.Font.helvetica();
        boldFont = pw.Font.helveticaBold();
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(1.5 * PdfPageFormat.cm),
          header: (context) => pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(bottom: 5 * PdfPageFormat.mm),
            decoration: const pw.BoxDecoration(
              border: pw.Border(bottom: pw.BorderSide(width: 0.5, color: PdfColors.grey300)),
            ),
            child: pw.Text(
              'KintaMed Edge Clinical Report | confidential',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
            ),
          ),
          footer: (context) => pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 10),
            child: pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount} | Generated by KintaMed Edge AI',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
            ),
          ),
          build: (pw.Context context) {
            return [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                   pw.Column(
                     crossAxisAlignment: pw.CrossAxisAlignment.start,
                     children: [
                       pw.Text("KintaMed Edge", style: pw.TextStyle(font: boldFont, fontSize: 28, color: PdfColors.blue900)),
                       pw.Text("Clinical Diagnostic Report", style: pw.TextStyle(font: font, fontSize: 14, color: PdfColors.grey700)),
                     ],
                   ),
                   pw.Column(
                     crossAxisAlignment: pw.CrossAxisAlignment.end,
                     children: [
                       pw.Text("Date: ${DateTime.now().toString().split(' ')[0]}", style: pw.TextStyle(font: font, fontSize: 10)),
                       pw.Text("Patient ID: ${assessment.patientId}", style: pw.TextStyle(font: font, fontSize: 10)),
                     ],
                   ),
                ],
              ),
              pw.SizedBox(height: 15),
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 10),

              // Patient Bio & Vitals Section
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(
                    flex: 1,
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text("Vitals Data", style: pw.TextStyle(font: boldFont, fontSize: 12)),
                        pw.SizedBox(height: 5),
                        _vitalRow("BP", "${assessment.systolic}/${assessment.diastolic} mmHg", font),
                        _vitalRow("Heart Rate", "${assessment.heartRate} bpm", font),
                        _vitalRow("SpO2", "${assessment.spo2}%", font),
                        _vitalRow("Temp", "${assessment.temperature}°C", font),
                      ],
                    ),
                  ),
                  pw.Expanded(
                    flex: 1,
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text("Clinical Specs", style: pw.TextStyle(font: boldFont, fontSize: 12)),
                        pw.SizedBox(height: 5),
                        if (assessment.glucose != null) _vitalRow("Glucose", "${assessment.glucose} mg/dL", font),
                        if (assessment.height != null) _vitalRow("Height", "${assessment.height} cm", font),
                        if (assessment.weight != null) _vitalRow("Weight", "${assessment.weight} kg", font),
                        _vitalRow("Allergies", assessment.allergies?.join(', ') ?? 'None reported', font),
                      ],
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 20),

              // Symptoms Section
              pw.Text("Primary Complaints & Symptoms:", style: pw.TextStyle(font: boldFont, fontSize: 12)),
              pw.SizedBox(height: 5),
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: const pw.BoxDecoration(
                  color: PdfColors.grey50,
                  borderRadius: pw.BorderRadius.all(pw.Radius.circular(5)),
                ),
                child: pw.Text(assessment.symptoms, style: pw.TextStyle(font: font, fontSize: 10)),
              ),
              pw.SizedBox(height: 20),

              // Triage Result Section
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 15),
                decoration: pw.BoxDecoration(
                  color: _getBgColor(assessment.urgencyColor),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
                  border: pw.Border.all(color: _getPdfColor(assessment.urgencyColor), width: 1),
                ),
                child: pw.Row(
                   mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                   children: [
                     pw.Text(
                       "TRIAGE CATEGORY: ${assessment.urgencyColor?.toUpperCase() ?? 'PENDING'}",
                       style: pw.TextStyle(font: boldFont, fontSize: 16, color: _getPdfColor(assessment.urgencyColor)),
                     ),
                     pw.Container(
                       width: 15,
                       height: 15,
                       decoration: pw.BoxDecoration(shape: pw.BoxShape.circle, color: _getPdfColor(assessment.urgencyColor)),
                     ),
                   ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Main AI Reasoning with Markdown formatting
              pw.Text("Clinical AI Assessment Reasoning:", style: pw.TextStyle(font: boldFont, fontSize: 14)),
              pw.SizedBox(height: 8),
              ..._buildMarkdown(assessment.aiPrediction ?? "Analysis pending.", font, boldFont),
              
              // Follow-up Chat History section
              if (chatHistory != null && chatHistory.length > 1) ...[
                pw.SizedBox(height: 30),
                pw.Text("Follow-up Clinical Discussion:", style: pw.TextStyle(font: boldFont, fontSize: 14)),
                pw.SizedBox(height: 10),
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 5),
                ...chatHistory.skip(1).map((msg) => _renderChatMessage(msg, font, boldFont)),
              ],

              pw.SizedBox(height: 40),
              pw.Divider(color: PdfColors.grey300),
              pw.Text(
                "DISCLAIMER: This report is generated by an Artificial Intelligence model (MedGemma) and is provided for supplementary clinical decision support. All findings must be verified by a licensed medical professional. Do not base treatment solely on this automated output.",
                style: pw.TextStyle(font: font, fontSize: 7, color: PdfColors.grey600),
                textAlign: pw.TextAlign.center,
              ),
            ];
          },
        ),
      );

      await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'KintaMed_Report_${assessment.id.substring(0, 8)}.pdf',
      );
    } catch (e) {
      print("PDF Generation Error: $e");
      rethrow;
    }
  }

  static pw.Widget _vitalRow(String label, String value, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.RichText(
        text: pw.TextSpan(
          children: [
            pw.TextSpan(text: "$label: ", style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
            pw.TextSpan(text: value, style: pw.TextStyle(font: font, fontSize: 9, fontWeight: pw.FontWeight.bold)),
          ],
        ),
      ),
    );
  }

  static pw.Widget _renderChatMessage(TriageChatMessage msg, pw.Font font, pw.Font boldFont) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: msg.isUser ? PdfColors.blue50 : PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
        border: pw.Border.all(color: msg.isUser ? PdfColors.blue100 : PdfColors.grey200),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            msg.isUser ? "Question (User):" : "Answer (KintaMed AI):",
            style: pw.TextStyle(font: boldFont, fontSize: 9, color: msg.isUser ? PdfColors.blue900 : PdfColors.grey900),
          ),
          pw.SizedBox(height: 4),
          ..._buildMarkdown(msg.text, font, boldFont),
        ],
      ),
    );
  }

  static List<pw.Widget> _buildMarkdown(String text, pw.Font font, pw.Font boldFont) {
    final lines = text.replaceAll("[ANALYSIS_COMPLETE]", "").trim().split('\n');
    final List<pw.Widget> widgets = [];
    
    for (var line in lines) {
      final trimmed = line.trim();
      if (trimmed.isEmpty) continue;

      // Header handling
      if (trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8, bottom: 4),
          child: pw.Text(trimmed.replaceAll('#', '').trim(), style: pw.TextStyle(font: boldFont, fontSize: 12, color: PdfColors.blue800)),
        ));
        continue;
      }

      // Bullet points
      if (trimmed.startsWith('* ') || trimmed.startsWith('- ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 10, bottom: 2),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("- ", style: pw.TextStyle(font: boldFont, fontSize: 10)),
              pw.Expanded(child: _renderFormattedText(trimmed.substring(2), font, boldFont)),
            ],
          ),
        ));
        continue;
      }

      // Standard paragraph
      widgets.add(pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: _renderFormattedText(trimmed, font, boldFont),
      ));
    }
    
    return widgets;
  }

  static pw.Widget _renderFormattedText(String text, pw.Font font, pw.Font boldFont) {
    // Sanitize text to remove unsupported characters like bullets
    final sanitized = text.replaceAll('•', '-');
    
    // Basic bold parsing: **text**
    final List<pw.InlineSpan> spans = [];
    final pattern = RegExp(r'\*\*(.*?)\*\*');
    int start = 0;
    
    for (final match in pattern.allMatches(sanitized)) {
      if (match.start > start) {
        spans.add(pw.TextSpan(text: sanitized.substring(start, match.start), style: pw.TextStyle(font: font, fontSize: 10)));
      }
      spans.add(pw.TextSpan(text: match.group(1), style: pw.TextStyle(font: boldFont, fontSize: 10)));
      start = match.end;
    }
    
    if (start < text.length) {
      spans.add(pw.TextSpan(text: text.substring(start), style: pw.TextStyle(font: font, fontSize: 10)));
    }
    
    return pw.RichText(text: pw.TextSpan(children: spans));
  }

  static PdfColor _getBgColor(String? color) {
    switch (color?.toLowerCase()) {
      case 'red': return PdfColors.red50;
      case 'yellow': return PdfColors.yellow50;
      case 'green': return PdfColors.green50;
      default: return PdfColors.blue50;
    }
  }

  static PdfColor _getPdfColor(String? color) {
    switch (color?.toLowerCase()) {
      case 'red':
        return PdfColors.red900;
      case 'yellow':
        return PdfColors.yellow900;
      case 'green':
        return PdfColors.green900;
      default:
        return PdfColors.blue900;
    }
  }
}
