platform :ios, '16.0'

use_frameworks! :linkage => :static

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Required for embedding models (TensorFlow Lite SelectTfOps)
    if target.name == 'Runner'
      target.build_configurations.each do |config|
        sdk = config.build_settings['SDKROOT']
        if sdk.nil? || !sdk.include?('simulator')
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_LDFLAGS'] << '-force_load'
          config.build_settings['OTHER_LDFLAGS'] << '$(PODS_ROOT)/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps'
        end
      end
    end
  end
end
