import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en', 'US'),
    Locale('fr', 'FR'),
    Locale('es', 'ES'),
    Locale('it', 'IT'),
    Locale('de', 'DE'),
    Locale('pt', 'PT'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en_US': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'App Settings',
      'return_to_dashboard': 'Return to Dashboard',
      'back_to_intake': 'Back to Intake',
      'Expert_care_slogan': 'Expert care, Clinical Intelligence, Anywhere.',
      // Home Screen
      'welcome': 'Welcome to',
      'tagline': 'AI-Powered Medical Triage at Your Fingertips',
      'start_assessment': 'Start New Assessment',
      'view_history': 'View Assessment History',
      'settings': 'Settings',
      'this_application_is_secure': 'This application is secure. All patient data is encrypted and remains on your device.',
      'Privacy_Policy': 'Privacy Policy',
      'Terms_of_Service': 'Terms of Service',
      'offline_ready_private': 'Offline Ready & Private',
      'preparing_clinical_intelligence': 'Preparing Clinical Intelligence',
      'ensuring_the_latest_medical_database_is_ready': 'Ensuring the latest medical database is ready.',
      'downloading_clinical_intelligence': 'Downloading Clinical Intelligence',
      'fetching_the_medical_reasoning_database': 'Fetching the medical reasoning database.',
      'download_failed': 'Download Failed',
      'connectivity_issue_detected': 'Connectivity issue detected. Tap the button below to retry.',
      'retry_download': 'Retry Download',
      // Intake Screen
      'step_1_patient_identity': 'Step 1: Patient Identity',
      'patient_intake': 'Patient Intake',
      'patient_information': 'Patient Information',
      'full_name': 'Full Name',
      'date_of_birth': 'Date of Birth',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'biological_sex': 'Biological Sex',
      'emergency_contact_phone': 'Emergency Contact Phone',
      'emergency_contact_name': 'Emergency Contact Name',
      'other': 'Other',
      'next_step': 'Next Step',
      'back': 'Back',
      'clinical_data_collection': 'Clinical Data Collection',

      // Allergies
      'step_2_allergies_sensitivities': 'Step 2: Allergies & Sensitivities',
      'please_check_all_that_apply_provide_details_if_selected': 'Please check all that apply. Provide details if selected.',
      'medication_allergies': 'Medication Allergies',
      'food_allergies': 'Food Allergies',
      'environmental_other': 'Environmental/Other Allergies',
      // Vitals
      'step_3_vital_signs': 'Step 3: Vital Signs',
      'reason_for_consultation': 'Reason for Consultation',
      'describe_the_patients_main_complaint': 'Describe the patient\'s main complaint',
      'please_enter_a_reason': 'Please enter a reason',
      'systolic': 'Systolic',
      'diastolic': 'Diastolic',
      'heart_rate': 'Heart Rate (bpm)',
      'temperature': 'Temperature (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glucose (mg/dL)',
      'height': 'Height (cm)',
      'weight': 'Weight (kg)',
      
      // Symptoms
      'symptoms_complaints': 'Symptoms & Complaints',
      'describe_symptoms': 'Describe symptoms in detail...',
      'tap_to_speak': 'Tap to speak',
      'listening': 'Listening...',
      
      // Medical History
      'medical_history': 'Medical History',
      'allergies': 'Allergies',
      'add_allergy': 'Add Allergy',
      'type_allergy': 'Type allergy name',
      
      // Clinical Media
      'step_4_visual_probe': 'Step 4: Visual Probe',
      'take_a_photo': 'Take a photo of any visible wound, rash or condition to assist the AI assessment.',
      'no_images_captured': 'No images captured',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'clinical_media': 'Clinical Media',
      'attach_images': 'Attach Images (X-rays, wounds, etc.)',
      'add_image': 'Add Image',
      'images_attached': 'image(s) attached',
      
      // Actions
      'submit_for_triage': 'Submit for AI Triage',
      'retry': 'Retry',
      'copy_text': 'Copy Text',
      'delete_redownload_model': 'Delete & Redownload Model',
      
      // Triage Screen
      'triage_analysis': 'Triage Analysis',
      'analyzing_clinical_data': 'Analyzing clinical data...',
      'initializing': 'Initialization...',
      'determining_category': 'DETERMINING CATEGORY...',
      'recommended_triage_category': 'Recommended Triage Category',
      'clinical_reasoning': 'Clinical Reasoning',
      'initializing_triage_engine': 'Initializing triage engine...',
      'follow_up_clinical_questions': 'Follow-up Clinical Questions',
      'ask_about_case': 'Ask about this case...',
      'you': 'You',
      'medical_ai': 'Medical AI',
      'share_pdf_report': 'Share PDF Report',
      'waking_up_ai_intelligence': 'Waking up AI Intelligence...',
      'return_to_dashboard': 'Return to Dashboard',
      'failed_to_generate_pdf': 'Failed to generate PDF', 
      'recommended_triage_category': 'Recommended Triage Category',
      'clinical_reasoning': 'Clinical Reasoning',
      'share_pdf_report': 'Share PDF Report',
      'follow_up_clinical_questions': 'Follow-up Clinical Questions',
      'ask_about_this_case': 'Ask about this case...',

      // Model Download
      'downloading_medical_model': 'Downloading Medical Model',
      'downloading_medgemma': 'Downloading MedGemma 3 Intelligence...',

      // Settings
      'ai_performance': 'AI Performance',
      'model_intelligence': 'Model Intelligence (maxTokens)',
      'model_intelligence_desc': 'Higher values produce longer, more detailed reasoning but use more RAM.',
      'fast': 'Fast',
      'detailed': 'Detailed',
      'current': 'Current',
      'hardware_acceleration': 'Hardware Acceleration',
      'hardware_acceleration_desc': 'GPU is faster but may crash on devices with less than 6GB RAM. CPU is safer for 4GB RAM devices.',
      'use_gpu_acceleration': 'Use GPU Acceleration',
      'enabled_experimental': 'Enabled (Experimental)',
      'disabled_software_mode': 'Disabled (Software Mode)',
      'optimization_tip': 'Optimization Tip',
      'optimization_tip_text': 'If the app closes during \'Analyzing...\', try lowering maxTokens to 256 and disabling GPU acceleration.',
      'visual_intelligence': 'Visual Intelligence',
      'multimodal_model_desc': 'Enables clinical image analysis (wounds, rashes) using Gemma 3 2B. Requires a high-performance device (>8GB RAM + GPU).',
      'download_visual_model': 'Download Visual Model',
      'delete_visual_model': 'Delete Visual Model',
      'high_performance_required': 'High Performance Required',
      'device_not_capable': 'Your device does not meet the minimum requirements (>8GB RAM + GPU) for advanced visual analysis.',
      'enable_visual_ai': 'Enable Visual AI',
      'vision_system_ready': 'Vision system ready',
      'requires_download': 'Requires model download (~2.5GB)',
      'model_management': 'Model Management',
      'model_management_desc': 'Manage the Gemma 3 Medical Multimodal model (4.5GB)',
      'model_downloaded': 'Model Downloaded',
      'model_missing': 'Model Missing',
      'system_ready': 'System ready for clinical analysis',
      'download_required': 'Download required to start triage',
      'download_model': 'Download Model',
      'delete_model': 'Delete Model',
      
      // Language Settings
      'language': 'Language',
      'language_desc': 'Choose your preferred language. AI responses will be in this language.',
      'english': 'English (US)',
      'french': 'French (FR)',
      'spanish': 'Spanish (ES)',
      'italian': 'Italian (IT)',
      'german': 'German (DE)',
      'portuguese': 'Portuguese (PT)',
      
      // Errors
      'inference_error': 'Inference Error',
      'error_message': 'The AI model encountered an error. Please copy this message for support:',
      'model_deleted_message': 'Model deleted. Please start intake again to re-download.',
      'failed_to_generate_pdf': 'Failed to generate PDF',
      'error_copied': 'Error copied to clipboard',
      
      // Time
      'waking_up_ai': 'Waking up AI Intelligence...',
      'usually_takes_time': 'This usually takes 10-30 seconds depending on device speed.',
      
      // History Screen
      'assessment_history': 'Assessment History',
      'assessment_details': 'Assessment Details',
      'search_patients': 'Search patients...',
      'no_history_found': 'No history found',
      'date': 'Date',
      'vitals': 'Vitals',
      'start_new_assessment': 'Start New Assessment',
      'delete_assessment': 'Delete Assessment',
      'confirm_delete': 'Are you sure you want to delete this assessment?',
      'delete': 'Delete',
      'cancel': 'Cancel',
      // Prompt construction
      'prompt_intro': 'Based on the following observations concerning the patient:',
      'prompt_age': 'Age:',
      'prompt_gender': 'Gender:',
      'prompt_vitals': 'Vitals:',
      'prompt_history_summary': 'Medical History Summary:',
      'prompt_begin_immediately': 'Begin your response IMMEDIATELY with the triage tag then',
      'prompt_images_analysis': 'provide a short analysis of the Clinical Images attached and',
      'prompt_treatment_plan': 'State your differential diagnosis and list the urgent actions and treatment plan for these symptoms:',
      'prompt_tokens_limit': 'tokens using this EXACT MarkDown structure:',
      'prompt_structure_triage': '[TRIAGE:RED] or [TRIAGE:YELLOW] or [TRIAGE:GREEN]',
      'prompt_structure_images': '## Clinical Images Analysis.',
      'prompt_structure_diagnosis': '## Differential Diagnosis & Urgent Actions.',
      'prompt_structure_concise_diagnosis': '### Concise Diagnosis:',
      'prompt_structure_explain_diagnoses': '(List and explain 2-3 possible diagnoses)',
      'prompt_structure_urgent_actions': '### Urgent Actions to take:',
      'prompt_structure_list_actions': '(List 3-5 urgent actions)',
      'prompt_structure_treatment_plan': '## Treatment plan:',
      'prompt_structure_list_steps': '(List 3-5 treatment steps)',
      'unknown': 'Unknown',
      'prompt_Glucose': 'Glucose',
      'prompt_Height': 'Height',
      'prompt_Weight': 'Weight',
      'prompt_Allergies': 'Allergies',
      'prompt_Question': 'Question: Respond always in',
      'prompt_in_less_than': 'in less than',
      'prompt_with_a_structured_markdown_response': 'Use a structured Markdown response.',
      'prompt_tokens': 'tokens',
    },
    
    'fr_FR': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'Paramètres de l\'application',
      'return_to_dashboard': 'Retour au tableau de bord',
      'back_to_intake': 'Retour à l\'admission',
      'Expert_care_slogan': 'Soins experts, intelligence clinique, partout.',
      // Home Screen
      'welcome': 'Bienvenue à',
      'tagline': 'Triage médical alimenté par l\'IA à portée de main',
      'start_assessment': 'Démarrer une nouvelle évaluation',
      'view_history': 'Voir l\'historique des évaluations',
      'settings': 'Paramètres',
      'this_application_is_secure': 'Cette application est sécurisée. Toutes les données des patients sont cryptées et restent sur votre appareil.',
      'Privacy_Policy': 'Politique de confidentialité',
      'Terms_of_Service': 'Conditions d\'utilisation',
      'offline_ready_private': 'Prêt hors ligne et privé',
      'preparing_clinical_intelligence': 'Préparation de l\'intelligence clinique',
      'ensuring_the_latest_medical_database_is_ready': 'Assurer que la dernière base de données médicale est prête.',
      'downloading_clinical_intelligence': 'Téléchargement de l\'intelligence clinique',
      'fetching_the_medical_reasoning_database': 'Récupération de la base de données de raisonnement médical.',
      'download_failed': 'Échec du téléchargement',
      'connectivity_issue_detected': 'Problème de connectivité détecté. Appuyez sur le bouton ci-dessous pour réessayer.',
      'retry_download': 'Réessayer le téléchargement',
      // Intake Screen
      'step_1_patient_identity': 'Étape 1 : Identité du patient',
      'patient_intake': 'Admission du patient',
      'patient_information': 'Informations sur le patient',
      'full_name': 'Nom complet',
      'date_of_birth': 'Date de naissance',
      'gender': 'Genre',
      'male': 'Homme',
      'female': 'Femme',
      'other': 'Autre',
      'first_name': 'Prénom',
      'last_name': 'Nom de famille',
      'biological_sex': 'Sexe biologique',
      'emergency_contact_phone': 'Téléphone du contact d\'urgence',
      'emergency_contact_name': 'Nom du contact d\'urgence',
      'other': 'Autre',
      'next_step': 'Prochaine étape',
      'back': 'Retour',
      'clinical_data_collection': 'Collecte de données cliniques',
      // Allergies
      'step_2_allergies_sensitivities': 'Étape 2 : Allergies et sensibilités',
      'please_check_all_that_apply_provide_details_if_selected': 'Veuillez cocher toutes les cases applicables. Fournissez les détails si sélectionnés.',
      'medication_allergies': 'Allergies médicamenteuses',
      'food_allergies': 'Allergies alimentaires',
      'environmental_other': 'Allergies environnementales/autres',
      // Vitals
      'step_3_vital_signs': 'Étape 3 : Signes vitaux',
      'reason_for_consultation': 'Raison de la consultation',
      'describe_the_patients_main_complaint': 'Décrivez la plainte principale du patient',
      'please_enter_a_reason': 'Veuillez entrer une raison',
      'systolic': 'Systolique',
      'diastolic': 'Diastolique',
      'heart_rate': 'Fréquence cardiaque (bpm)',
      'temperature': 'Température (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glucose (mg/dL)',
      'height': 'Taille (cm)',
      'weight': 'Poids (kg)',
      
      // Symptoms
      'symptoms_complaints': 'Symptômes et plaintes',
      'describe_symptoms': 'Décrivez les symptômes en détail...',
      'tap_to_speak': 'Appuyez pour parler',
      'listening': 'Écoute...',
      
      // Medical History
      'medical_history': 'Antécédents médicaux',
      'allergies': 'Allergies',
      'add_allergy': 'Ajouter une allergie',
      'type_allergy': 'Saisir le nom de l\'allergie',
      
      // Clinical Media
      'step_4_visual_probe': 'Étape 4 : Sonde visuelle',
      'take_a_photo': 'Prenez une photo de toute plaie, éruption cutanée ou affection visible pour aider à l\'évaluation par l\'IA.',
      'no_images_captured': 'Aucune image capturée',
      'camera': 'Caméra',
      'gallery': 'Galerie',
      'clinical_media': 'Médias cliniques',
      'attach_images': 'Joindre des images (radiographies, plaies, etc.)',
      'add_image': 'Ajouter une image',
      'images_attached': 'image(s) jointe(s)',
      
      // Actions
      'submit_for_triage': 'Soumettre pour triage IA',
      'retry': 'Réessayer',
      'copy_text': 'Copier le texte',
      'delete_redownload_model': 'Supprimer et retélécharger le modèle',
      
      // Triage Screen
      'triage_analysis': 'Analyse de triage',
      'analyzing_clinical_data': 'Analyse des données cliniques...',
      'initializing': 'Initialisation...',
      'determining_category': 'DÉTERMINATION DE LA CATÉGORIE...',
      'recommended_triage_category': 'Catégorie de triage recommandée',
      'clinical_reasoning': 'Raisonnement clinique',
      'initializing_triage_engine': 'Initialisation du moteur de triage...',
      'follow_up_clinical_questions': 'Questions cliniques de suivi',
      'ask_about_case': 'Poser une question sur ce cas...',
      'you': 'Vous',
      'medical_ai': 'IA médicale',
      'share_pdf_report': 'Partager le rapport PDF',
      'waking_up_ai_intelligence': 'Éveil de l\'intelligence artificielle...',  
      'return_to_dashboard': 'Retour au tableau de bord',
      'failed_to_generate_pdf': 'Échec de la génération du PDF', 
      'recommended_triage_category': 'Catégorie de triage recommandée',
      'clinical_reasoning': 'Raisonnement clinique',
      'share_pdf_report': 'Partager le rapport PDF',
      'follow_up_clinical_questions': 'Questions cliniques de suivi',
      'ask_about_this_case': ' Poser une question sur ce cas...',
      
      // Model Download
      'downloading_medical_model': 'Téléchargement du modèle médical',
      'downloading_medgemma': 'Téléchargement de MedGemma 3 Intelligence...',
      
      // Settings
      'ai_performance': 'Performance de l\'IA',
      'model_intelligence': 'Intelligence du modèle (maxTokens)',
      'model_intelligence_desc': 'Des valeurs plus élevées produisent un raisonnement plus long et plus détaillé mais utilisent plus de RAM.',
      'fast': 'Rapide',
      'detailed': 'Détaillé',
      'current': 'Actuel',
      'hardware_acceleration': 'Accélération matérielle',
      'hardware_acceleration_desc': 'Le GPU est plus rapide mais peut planter sur les appareils avec moins de 6 Go de RAM. Le CPU est plus sûr pour les appareils de 4 Go de RAM.',
      'use_gpu_acceleration': 'Utiliser l\'accélération GPU',
      'enabled_experimental': 'Activé (Expérimental)',
      'disabled_software_mode': 'Désactivé (Mode logiciel)',
      'optimization_tip': 'Conseil d\'optimisation',
      'optimization_tip_text': 'Si l\'application se ferme pendant \'Analyse...\', essayez de réduire maxTokens à 256 et de désactiver l\'accélération GPU.',
      'visual_intelligence': 'Intelligence Visuelle',
      'multimodal_model_desc': 'Active l\'analyse d\'images cliniques (plaies, éruptions) via Gemma 3 2B. Nécessite au moins 8 Go de RAM et un GPU.',
      'download_visual_model': 'Télécharger le modèle visuel',
      'delete_visual_model': 'Supprimer le modèle visuel',
      'high_performance_required': 'Haute performance requise',
      'device_not_capable': 'Votre appareil ne répond pas aux critères minimum (>8 Go RAM + GPU) pour l\'IA visuelle avancée.',
      'enable_visual_ai': 'Activer l\'IA Visuelle',
      'vision_system_ready': 'Système de vision prêt',
      'requires_download': 'Nécessite le téléchargement du modèle (~2.5 Go)',
      'model_management': 'Gestion des modèles',
      'model_management_desc': 'Gérer le modèle multimodal médical Gemma 3 (4.5 Go)',
      'model_downloaded': 'Modèle téléchargé',
      'model_missing': 'Modèle manquant',
      'system_ready': 'Système prêt pour l\'analyse clinique',
      'download_required': 'Téléchargement requis pour commencer le triage',
      'download_model': 'Télécharger le modèle',
      'delete_model': 'Supprimer le modèle',
      
      // Language Settings
      'language': 'Langue',
      'language_desc': 'Choisissez votre langue préférée. Les réponses de l\'IA seront dans cette langue.',
      'english': 'Anglais (US)',
      'french': 'Français (FR)',
      'spanish': 'Espagnol (ES)',
      'italian': 'Italien (IT)',
      'german': 'Allemand (DE)',
      'portuguese': 'Portugais (PT)',
      
      // Errors
      'inference_error': 'Erreur d\'inférence',
      'error_message': 'Le modèle IA a rencontré une erreur. Veuillez copier ce message pour le support :',
      'model_deleted_message': 'Modèle supprimé. Veuillez recommencer l\'admission pour retélécharger.',
      'failed_to_generate_pdf': 'Échec de la génération du PDF',
      'error_copied': 'Erreur copiée dans le presse-papiers',
      
      // Time
      'waking_up_ai': 'Réveil de l\'intelligence IA...',
      'usually_takes_time': 'Cela prend généralement 10 à 30 secondes selon la vitesse de l\'appareil.',
      
      // History Screen
      'assessment_history': 'Historique des évaluations',
      'assessment_details': 'Détails de l\'évaluation',
      'search_patients': 'Rechercher des patients...',
      'no_history_found': 'Aucun historique trouvé',
      'date': 'Date',
      'vitals': 'Signes vitaux',
      'start_new_assessment': 'Démarrer une nouvelle évaluation',
      'delete_assessment': 'Supprimer l\'évaluation',
      'confirm_delete': 'Êtes-vous sûr de vouloir supprimer cette évaluation ?',
      'delete': 'Supprimer',
      'cancel': 'Annuler',
      // Prompt construction
      'prompt_intro': 'Sur la base des observations suivantes concernant le patient :',
      'prompt_age': 'Âge :',
      'prompt_gender': 'Genre :',
      'prompt_vitals': 'Constantes :',
      'prompt_history_summary': 'Résumé de l\'historique médical :',
      'prompt_begin_immediately': 'Commencez votre réponse IMMÉDIATEMENT avec la balise de triage, puis',
      'prompt_images_analysis': 'fournissez une courte analyse des images cliniques jointes et',
      'prompt_treatment_plan': 'donnez votre diagnostic différentiel, les actions urgentes et le plan de traitement pour ce symptôme :',
      'prompt_tokens_limit': 'tokens en utilisant cette structure MarkDown EXACTE :',
      'prompt_structure_triage': '[TRIAGE:RED] ou [TRIAGE:YELLOW] ou [TRIAGE:GREEN]',
      'prompt_structure_images': '## Analyse des images cliniques.',
      'prompt_structure_diagnosis': '## Diagnostic différentiel et actions urgentes.',
      'prompt_structure_concise_diagnosis': '### Diagnostic concis :',
      'prompt_structure_explain_diagnoses': '(Énumérez et expliquez 2-3 diagnostics possibles)',
      'prompt_structure_urgent_actions': '### Actions urgentes à prendre :',
      'prompt_structure_list_actions': '(Énumérez 3-5 actions urgentes)',
      'prompt_structure_treatment_plan': '## Plan de traitement :',
      'prompt_structure_list_steps': '(Énumérez 3-5 étapes de traitement)',
      'unknown': 'Inconnu',
      'prompt_Glucose': 'Glucose',
      'prompt_Height': 'Taille',
      'prompt_Weight': 'Poids',
      'prompt_Allergies': 'Allergies',
      'prompt_Question': 'Question: Répondez toujours en',  
      'prompt_in_less_than': 'en moins de',
      'prompt_with_a_structured_markdown_response': 'avec une réponse structurée en Markdown.',
      'prompt_tokens': 'tokens',
    },
    
    'es_ES': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'Configuración de la aplicación',
      'return_to_dashboard': 'Volver al panel',
      'back_to_intake': 'Volver a admisión',
      'Expert_care_slogan': 'Atención experta, inteligencia clínica, en todas partes.',
      // Home Screen
      'welcome': 'Bienvenido a',
      'tagline': 'Triaje médico impulsado por IA al alcance de tu mano',
      'start_assessment': 'Iniciar nueva evaluación',
      'view_history': 'Ver historial de evaluaciones',
      'settings': 'Configuración',
      'this_application_is_secure': 'Esta aplicación es segura. Todos los datos del paciente están encriptados y permanecen en su dispositivo.',
      'Privacy_Policy': 'Política de privacidad',
      'Terms_of_Service': 'Condiciones de uso',
      'offline_ready_private': 'Listo sin conexión y privado',
      'preparing_clinical_intelligence': 'Preparación de la inteligencia clínica',
      'ensuring_the_latest_medical_database_is_ready': 'Asegurar que la última base de datos médica esté lista.',
      'downloading_clinical_intelligence': 'Descarga de la inteligencia clínica',
      'fetching_the_medical_reasoning_database': 'Recuperación de la base de datos de razonamiento médico.',
      'download_failed': 'Fallo en la descarga',
      'connectivity_issue_detected': 'Se ha detectado un problema de conectividad. Pulse el botón de abajo para reintentar.',
      'retry_download': 'Reintentar descarga',
      // Intake Screen
      'step_1_patient_identity': 'Paso 1: Identidad del paciente',
      'patient_intake': 'Admisión del paciente',
      'patient_information': 'Información del paciente',
      'full_name': 'Nombre completo',
      'date_of_birth': 'Fecha de nacimiento',
      'gender': 'Género',
      'male': 'Masculino',
      'female': 'Fem enino',
      'other': 'Otro',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'biological_sex': 'Sexo biológico',
      'emergency_contact_phone': 'Teléfono del contacto de emergencia',
      'emergency_contact_name': 'Nombre del contacto de emergencia',
      'other': 'Otro',
      'next_step': 'Próximo paso',
      'back': 'Volver',
      'clinical_data_collection': 'Recolección de datos clínicos',
      // Allergies
      'step_2_allergies_sensitivities': 'Paso 2: Allergies et sensibilités',
      'please_check_all_that_apply_provide_details_if_selected': 'Por favor, marque todas las casillas aplicables. Proporcione los detalles si están seleccionados.',
      'medication_allergies': 'Alergias medicamentosas',
      'food_allergies': 'Alergias alimentarias',
      'environmental_other': 'Alergias ambientales/otras',
      // Vitals
      'step_3_vital_signs': 'Paso 3: Signes vitaux',
      'reason_for_consultation': 'Razón de la consulta',
      'describe_the_patients_main_complaint': 'Décrivez la plainte principale du patient',
      'please_enter_a_reason': 'Por favor, introduzca una razón',
      'systolic': 'Sistólica',
      'diastolic': 'Diastólica',
      'heart_rate': 'Frecuencia cardíaca (lpm)',
      'temperature': 'Temperatura (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glucosa (mg/dL)',
      'height': 'Altura (cm)',
      'weight': 'Peso (kg)',
      
      // Symptoms
      'symptoms_complaints': 'Síntomas y quejas',
      'describe_symptoms': 'Describe los síntomas en detalle...',
      'tap_to_speak': 'Toca para hablar',
      'listening': 'Escuchando...',
      
      // Medical History
      'medical_history': 'Historial médico',
      'allergies': 'Alergias  ',
      'add_allergy': 'Agregar alergia',
      'type_allergy': 'Escribe el nombre de la alergia',
      
      // Clinical Media
      'step_4_visual_probe': 'Paso 4: Sonde visual',
      'take_a_photo': 'Toma una foto de cualquier herida, erupción o afección visible para ayudar a la evaluación de la IA.',
      'no_images_captured': 'No se han capturado imágenes',
      'camera': 'Cámara',
      'gallery': 'Galería', 
      'clinical_media': 'Medios clínicos',
      'attach_images': 'Adjuntar imágenes (radiografías, heridas, etc.)',
      'add_image': 'Agregar imagen',
      'images_attached': 'imagen(es) adjunta(s)',
      
      // Actions
      'submit_for_triage': 'Enviar para triaje IA',
      'retry': 'Reintentar',
      'copy_text': 'Copiar texto',
      'delete_redownload_model': 'Eliminar y volver a descargar el modelo',
      
      // Triage Screen
      'triage_analysis': 'Análisis de triaje',
      'analyzing_clinical_data': 'Analizando datos clínicos...',
      'initializing': 'Inicializando...',
      'determining_category': 'DETERMINANDO CATEGORÍA...',
      'recommended_triage_category': 'Categoría de triaje recomendada',
      'clinical_reasoning': 'Razonamiento clínico',
      'initializing_triage_engine': 'Inicializando motor de triaje...',
      'follow_up_clinical_questions': 'Preguntas clínicas de seguimiento',
      'ask_about_case': 'Preguntar sobre este caso...',
      'you': 'Tú',
      'medical_ai': 'IA médica',
      'share_pdf_report': 'Compartir informe PDF',
      'waking_up_ai_intelligence': 'Despertando la inteligencia artificial...', 
      'return_to_dashboard': 'Volver al panel',
      'failed_to_generate_pdf': 'Fallo al generar el PDF', 
      'recommended_triage_category': 'Categoría de triaje recomendada',
      'clinical_reasoning': 'Razonamiento clínico',
      'share_pdf_report': 'Compartir informe PDF',
      'follow_up_clinical_questions': 'Preguntas clínicas de seguimiento',
      'ask_about_this_case': 'Preguntar sobre este caso...',
      
      // Model Download
      'downloading_medical_model': 'Descargando modelo médico',
      'downloading_medgemma': 'Descargando MedGemma 3 Intelligence...',
      
      // Settings
      'ai_performance': 'Rendimiento de IA',
      'model_intelligence': 'Inteligencia del modelo (maxTokens)',
      'model_intelligence_desc': 'Valores más altos producen razonamiento más largo y detallado pero usan más RAM.',
      'fast': 'Rápido',
      'detailed': 'Detallado',
      'current': 'Actual',
      'hardware_acceleration': 'Aceleración de hardware',
      'hardware_acceleration_desc': 'GPU es más rápido pero puede fallar en dispositivos con menos de 6GB de RAM. CPU es más seguro para dispositivos de 4GB de RAM.',
      'use_gpu_acceleration': 'Usar aceleración GPU',
      'enabled_experimental': 'Habilitado (Experimental)',
      'disabled_software_mode': 'Deshabilitado (Modo software)',
      'optimization_tip': 'Consejo de optimización',
      'optimization_tip_text': 'Si la aplicación se cierra durante \'Analizando...\', intenta reducir maxTokens a 256 y deshabilitar la aceleración GPU.',
      'model_management': 'Gestión de modelos',
      'model_management_desc': 'Descargar el modelo multimodal médico Gemma 3 (4.5 Go)',
      'model_downloaded': 'Modelo descargado',
      'model_missing': 'Modelo faltante',
      'system_ready': 'Sistema listo para el análisis clínico',
      'download_required': 'Descarga requerida para comenzar el triaje',
      'download_model': 'Descargar modelo',
      'delete_model': 'Eliminar modelo',
      
      // Language Settings
      'language': 'Idioma',
      'language_desc': 'Elige tu idioma preferido. Las respuestas de IA estarán en este idioma.',
      'english': 'Inglés (US)',
      'french': 'Francés (FR)',
      'spanish': 'Español (ES)',
      'italian': 'Italiano (IT)',
      'german': 'Alemán (DE)',
      'portuguese': 'Portugués (PT)',
      
      // Errors
      'inference_error': 'Error de inferencia',
      'error_message': 'El modelo de IA encontró un error. Por favor copia este mensaje para soporte:',
      'model_deleted_message': 'Modelo eliminado. Por favor inicia la admisión nuevamente para volver a descargar.',
      'failed_to_generate_pdf': 'Error al generar PDF',
      'error_copied': 'Error copiado al portapapeles',
      
      // Time
      'waking_up_ai': 'Despertando inteligencia IA...',
      'usually_takes_time': 'Esto generalmente toma 10-30 segundos dependiendo de la velocidad del dispositivo.',
      
      // History Screen
      'assessment_history': 'Historial de evaluaciones',
      'assessment_details': 'Detalles de la evaluación',
      'search_patients': 'Buscar pacientes...',
      'no_history_found': 'No se encontró historial',
      'date': 'Fecha',
      'vitals': 'Signos vitales',
      'start_new_assessment': 'Iniciar nueva evaluación',
      'delete_assessment': 'Eliminar evaluación',
      'confirm_delete': '¿Está seguro de que desea eliminar esta evaluación?',
      'delete': 'Eliminar',
      'cancel': 'Cancelar',
      // Prompt construction
      'prompt_intro': 'Basado en las siguientes observaciones sobre el paciente:',
      'prompt_age': 'Edad:',
      'prompt_gender': 'Género:',
      'prompt_vitals': 'Signos vitales:',
      'prompt_history_summary': 'Resumen del historial médico:',
      'prompt_begin_immediately': 'Comience su respuesta INMEDIATAMENTE con la etiqueta de triaje, luego',
      'prompt_images_analysis': 'proporcione un breve análisis de las imágenes clínicas adjuntas y',
      'prompt_treatment_plan': 'proporcione su diagnóstico diferencial, acciones urgentes y plan de tratamiento para este síntoma:',
      'prompt_tokens_limit': 'tokens utilizando esta estructura MarkDown EXACTA:',
      'prompt_structure_triage': '[TRIAGE:RED] o [TRIAGE:YELLOW] o [TRIAGE:GREEN]',
      'prompt_structure_images': '## Análisis de imágenes clínicas.',
      'prompt_structure_diagnosis': '## Diagnóstico diferencial y acciones urgentes.',
      'prompt_structure_concise_diagnosis': '### Diagnóstico conciso:',
      'prompt_structure_explain_diagnoses': '(Enumere y explique 2-3 diagnósticos posibles)',
      'prompt_structure_urgent_actions': '### Acciones urgentes a tomar:',
      'prompt_structure_list_actions': '(Enumere 3-5 acciones urgentes)',
      'prompt_structure_treatment_plan': '## Plan de tratamiento:',
      'prompt_structure_list_steps': '(Enumere 3-5 pasos de tratamiento)',
      'unknown': 'Desconocido',
      'prompt_Glucose': 'Glucosa',
      'prompt_Height': 'Estatura',
      'prompt_Weight': 'Peso', 
      'prompt_Allergies': 'Alergias',
      'prompt_Question': 'Question: Responde siempre en',  
      'prompt_in_less_than': 'en menos de',
      'prompt_with_a_structured_markdown_response': 'con una respuesta estructurada en Markdown.',
      'prompt_tokens': 'tokens',
    },
    
    'it_IT': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'Impostazioni dell\'app',
      'return_to_dashboard': 'Torna alla dashboard',
      'back_to_intake': 'Torna all\'ammissione',
      'Expert_care_slogan': 'Cura esperta, intelligenza clinica, ovunque.',
      // Home Screen
      'welcome': 'Benvenuto a',
      'tagline': 'Triage medico basato su IA a portata di mano',
      'start_assessment': 'Inizia nuova valutazione',
      'view_history': 'Visualizza cronologia valutazioni',
      'settings': 'Impostazioni',
      'this_application_is_secure': 'Questa applicazione è sicura. Tutti i dati del paziente sono crittografati e rimangono sul tuo dispositivo.',
      'Privacy_Policy': 'Politica sulla riservatezza',
      'Terms_of_Service': 'Termini di servizio',  
      'offline_ready_private': 'Pronto offline e privato',
      'preparing_clinical_intelligence': 'Preparazione dell\'intelligenza clinica',
      'ensuring_the_latest_medical_database_is_ready': 'Assicurare che l\'ultima base di dati medica sia pronta.',
      'downloading_clinical_intelligence': 'Download dell\'intelligenza clinica',
      'fetching_the_medical_reasoning_database': 'Recupero della base di dati di ragionamento medico.',
      'download_failed': 'Download fallito',
      'connectivity_issue_detected': 'Problema di connettività rilevato. Toccare il pulsante sottostante per riprovare.',
      'retry_download': 'Riprova download',

      // Intake Screen
      'step_1_patient_identity': 'Passo 1: Identità del paziente',
      'patient_intake': 'Ammissione paziente',
      'patient_information': 'Informazioni paziente',
      'full_name': 'Nome completo',
      'date_of_birth': 'Data di nascita',
      'gender': 'Genere',
      'male': 'Maschio',
      'female': 'Femmina',
      'other': 'Altro',
      'first_name': 'Nome',
      'last_name': 'Cognome',
      'biological_sex': 'Sesso biologico',
      'emergency_contact_phone': 'Telefono del contatto di emergenza',
      'emergency_contact_name': 'Nome del contatto di emergenza',
      'other': 'Altro',
      'next_step': 'Prossimo passo',
      'back': 'Indietro',
      'clinical_data_collection': 'Raccolta di dati clinici',
      // Allergies
      'step_2_allergies_sensitivities': 'Passo 2: Allergie e sensibilità',
      'please_check_all_that_apply_provide_details_if_selected': 'Si prega di selezionare tutte le opzioni applicabili. Fornire i dettagli se selezionato.',
      'medication_allergies': 'Allergie ai farmaci',
      'food_allergies': 'Allergie alimentari',
      'environmental_other': 'Allergie ambientali/altre',  
      // Vitals
      'step_3_vital_signs': 'Passo 3: Sinais vitais',
      'reason_for_consultation': 'Motivo della consultazione',
      'describe_the_patients_main_complaint': 'Descrivere la principale lamentela del paziente',
      'please_enter_a_reason': 'Si prega di inserire una ragione',
      'systolic': 'Sistólica',
      'diastolic': 'Diastólica',
      'heart_rate': 'Frequenza cardiaca (bpm)',
      'temperature': 'Temperatura (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glucosio (mg/dL)',
      'height': 'Altezza (cm)',
      'weight': 'Peso (kg)',  
      
      // Symptoms
      'symptoms_complaints': 'Sintomi e reclami',
      'describe_symptoms': 'Descrivi i sintomi in dettaglio...',
      'tap_to_speak': 'Tocca per parlare',
      'listening': 'In ascolto...',
      
      // Medical History
      'medical_history': 'Storia medica',
      'allergies': 'Allergie',
      'add_allergy': 'Aggiungi allergia',
      'type_allergy': 'Digita il nome dell\'allergia',
      
      // Clinical Media
      'step_4_visual_probe': 'Passo 4: Sonde visuelle',
      'take_a_photo': 'Scatta una foto di qualsiasi ferita, eruzione cutanea o condizione visibile per aiutare la valutazione dell\'IA.',
      'no_images_captured': 'Nessuna immagine catturata',
      'camera': 'Fotocamera',
      'gallery': 'Galleria',  
      'clinical_media': 'Media clinici',
      'attach_images': 'Allega immagini (radiografie, ferite, ecc.)',
      'add_image': 'Aggiungi immagine',
      'images_attached': 'immagine/i allegata/e',
      
      // Actions
      'submit_for_triage': 'Invia per triage IA',
      'retry': 'Riprova',
      'copy_text': 'Copia testo',
      'delete_redownload_model': 'Elimina e riscarica il modello',
      
      // Triage Screen
      'triage_analysis': 'Analisi di triage',
      'analyzing_clinical_data': 'Analisi dei dati clinici...',
      'initializing': 'Inizializzazione...',
      'determining_category': 'DETERMINAZIONE CATEGORIA...',
      'recommended_triage_category': 'Categoria di triage raccomandata',
      'clinical_reasoning': 'Ragionamento clinico',
      'initializing_triage_engine': 'Inizializzazione motore di triage...',
      'follow_up_clinical_questions': 'Domande cliniche di follow-up',
      'ask_about_case': 'Chiedi informazioni su questo caso...',
      'you': 'Tu',
      'medical_ai': 'IA medica',
      'share_pdf_report': 'Condividi report PDF',
      'waking_up_ai_intelligence': 'Risveglio dell\'intelligenza artificiale...', 
      'return_to_dashboard': 'Torna al pannello',
      'failed_to_generate_pdf': 'Impossibile generare il PDF', 
      'recommended_triage_category': 'Categoria di triage raccomandata',
      'clinical_reasoning': 'Ragionamento clinico',
      'share_pdf_report': 'Condividi report PDF',
      'follow_up_clinical_questions': 'Domande cliniche di follow-up',
      'ask_about_this_case': 'Chiedi informazioni su questo caso...',
     
      
      // Model Download
      'downloading_medical_model': 'Download modello medico',
      'downloading_medgemma': 'Download MedGemma 3 Intelligence...',
      
      // Settings
      'ai_performance': 'Prestazioni IA',
      'model_intelligence': 'Intelligenza del modello (maxTokens)',
      'model_intelligence_desc': 'Valori più alti producono ragionamenti più lunghi e dettagliati ma usano più RAM.',
      'fast': 'Veloce',
      'detailed': 'Dettagliato',
      'current': 'Corrente',
      'hardware_acceleration': 'Accelerazione hardware',
      'hardware_acceleration_desc': 'GPU è più veloce ma può bloccarsi su dispositivi con meno di 6GB di RAM. CPU è più sicuro per dispositivi da 4GB di RAM.',
      'use_gpu_acceleration': 'Usa accelerazione GPU',
      'enabled_experimental': 'Abilitato (Sperimentale)',
      'disabled_software_mode': 'Disabilitato (Modalità software)',
      'optimization_tip': 'Suggerimento di ottimizzazione',
      'optimization_tip_text': 'Se l\'app si chiude durante \'Analisi...\', prova a ridurre maxTokens a 256 e disabilitare l\'accelerazione GPU.',
      'model_management': 'Gestione dei modelli',
      'model_management_desc': 'Scarica il modello multimodale medico Gemma 3 (4.5 Go)',
      'model_downloaded': 'Modello scaricato',
      'model_missing': 'Modello mancante',
      'system_ready': 'Sistema pronto per l\'analyse clinique',
      'download_required': 'Download richiesto per i niziare il triage',
      'download_model': 'Scarica modello',
      'delete_model': 'Elimina modello',
      
      // Language Settings
      'language': 'Lingua',
      'language_desc': 'Scegli la tua lingua preferita. Le risposte dell\'IA saranno in questa lingua.',
      'english': 'Inglese (US)',
      'french': 'Francese (FR)',
      'spanish': 'Spagnolo (ES)',
      'italian': 'Italiano (IT)',
      'german': 'Tedesco (DE)',
      'portuguese': 'Portoghese (PT)',
      
      // Errors
      'inference_error': 'Errore di inferenza',
      'error_message': 'Il modello IA ha riscontrato un errore. Si prega di copiare questo messaggio per il supporto:',
      'model_deleted_message': 'Modello eliminato. Si prega di iniziare nuovamente l\'ammissione per scaricare di nuovo.',
      'failed_to_generate_pdf': 'Impossibile generare PDF',
      'error_copied': 'Errore copiato negli appunti',
      
      // Time
      'waking_up_ai': 'Risveglio dell\'intelligenza IA...',
      'usually_takes_time': 'Questo richiede solitamente 10-30 secondi a seconda della velocità del dispositivo.',
      
      // History Screen
      'assessment_history': 'Cronologia valutazioni',
      'search_patients': 'Cerca pazienti...',
      'no_history_found': 'Nessuna cronologia trovata',
      'delete_assessment': 'Elimina valutazione',
      'confirm_delete': 'Sei sicuro di voler eliminare questa valutazione?',
      'delete': 'Elimina',
      'cancel': 'Annulla',
      // Prompt construction
      'prompt_intro': 'Sulla base delle seguenti osservazioni riguardanti il paziente:',
      'prompt_age': 'Età:',
      'prompt_gender': 'Genere:',
      'prompt_vitals': 'Parametri vitali:',
      'prompt_history_summary': 'Riepilogo della storia medica:',
      'prompt_begin_immediately': 'Inizia la tua risposta IMMEDIATAMENTE con il tag di triage, quindi',
      'prompt_images_analysis': 'fornisci una breve analisi delle immagini cliniche allegate e',
      'prompt_treatment_plan': 'fornisci la tua diagnosi differenziale, le azioni urgenti e il piano di trattamento per questo sintomo:',
      'prompt_tokens_limit': 'token utilizzando questa ESATTA struttura MarkDown:',
      'prompt_structure_triage': '[TRIAGE:RED] o [TRIAGE:YELLOW] o [TRIAGE:GREEN]',
      'prompt_structure_images': '## Analisi delle immagini cliniche.',
      'prompt_structure_diagnosis': '## Diagnosi differenziale e azioni urgenti.',
      'prompt_structure_concise_diagnosis': '### Diagnosi concisa:',
      'prompt_structure_explain_diagnoses': '(Elenca e spiega 2-3 diagnosi possibili)',
      'prompt_structure_urgent_actions': '### Azioni urgenti da intraprendere:',
      'prompt_structure_list_actions': '(Elenca 3-5 azioni urgenti)',
      'prompt_structure_treatment_plan': '## Piano di trattamento:',
      'prompt_structure_list_steps': '(Elenca 3-5 fasi del trattamento)',
      'unknown': 'Sconosciuto',
      'prompt_Glucose': 'Glucosio',
      'prompt_Height': 'Altezza',
      'prompt_Weight': 'Peso',
      'prompt_Allergies': 'Allergie',
      'prompt_Question': 'Domanda: Rispondi sempre in',
      'prompt_in_less_than': 'in meno di',
      'prompt_with_a_structured_markdown_response': 'con una risposta strutturata in Markdown.',
      'prompt_tokens': 'token',
    },
    
    'de_DE': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'App-Einstellungen',
      'return_to_dashboard': 'Zurück zum Dashboard',
      'back_to_intake': 'Zurück zur Aufnahme',
      'Expert_care_slogan': 'Fachkundige Versorgung, klinische Intelligenz, überall.',
      // Home Screen
      'welcome': 'Willkommen bei',
      'tagline': 'KI-gestützte medizinische Triage zur Hand',
      'start_assessment': 'Neue Bewertung starten',
      'view_history': 'Bewertungsverlauf anzeigen',
      'settings': 'Einstellungen',
      'this_application_is_secure': 'Diese Anwendung ist sicher. Alle Patientendaten werden verschlüsselt und bleiben auf Ihrem Gerät.',
      'Privacy_Policy': 'Datenschutzrichtlinie',
      'Terms_of_Service': 'Nutzungsbedingungen',
      'offline_ready_private': 'Offline bereit und privat',
      'preparing_clinical_intelligence': 'Vorbereitung der klinischen Intelligenz',
      'ensuring_the_latest_medical_database_is_ready': 'Sicherstellen, dass die neueste medizinische Datenbank bereit ist.',
      'downloading_clinical_intelligence': 'Herunterladen der klinischen Intelligenz',
      'fetching_the_medical_reasoning_database': 'Abrufen der medizinischen Argumentationsdatenbank.',
      'download_failed': 'Download fehlgeschlagen',
      'connectivity_issue_detected': 'Konnektivitätsproblem erkannt. Tippen Sie auf die Schaltfläche unten, um es erneut zu versuchen.',
      'retry_download': 'Erneut herunterladen',
      // Intake Screen
      'step_1_patient_identity': 'Schritt 1: Patientenidentität',
      'patient_intake': 'Patientenaufnahme',
      'patient_information': 'Patienteninformationen',
      'full_name': 'Vollständiger Name',
      'date_of_birth': 'Geburtsdatum',
      'gender': 'Geschlecht',
      'male': 'Männlich',
      'female': 'Weiblich',
      'other': 'Andere',
      'first_name': 'Vorname',
      'last_name': 'Nachname',
      'biological_sex': 'Biologisches Geschlecht',
      'emergency_contact_phone': 'Notfalltelefonnummer',
      'emergency_contact_name': 'Name des Notfallkontakts',
      'other': 'Sonstiges',
      'next_step': 'Nächster Schritt',
      'back': 'Zurück',
      'clinical_data_collection': 'Erhebung klinischer Daten',

      // Allergien
      'step_2_allergies_sensitivities': 'Schritt 2: Allergien und Unverträglichkeiten',
      'please_check_all_that_apply_provide_details_if_selected': 'Bitte alle zutreffenden Punkte ankreuzen. Geben Sie gegebenenfalls Details an.',
      'medication_allergies': 'Medikamentenallergien',
      'food_allergies': 'Nahrungsmittelallergien',
      'environmental_other': 'Umweltallergien/Sonstige Allergien',
      // Vitals
      'step_3_vital_signs': 'Schritt 3: Vitalparameter',
      'reason_for_consultation': 'Grund der Konsultation',
      'describe_the_patients_main_complaint': 'Beschreiben Sie die Hauptbeschwerde des Patienten',
      'please_enter_a_reason': 'Bitte geben Sie einen Grund ein',
      'systolic': 'Sistólica',
      'diastolic': 'Diastólica',
      'heart_rate': ' Herzfrequenz (l/min)',
      'temperature': 'Temperatur (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glukose (mg/dL)',
      'height': 'Größe (cm)',
      'weight': 'Gewicht (kg)',    
      // Symptoms
      'symptoms_complaints': 'Symptome und Beschwerden',
      'describe_symptoms': 'Beschreiben Sie die Symptome im Detail...',
      'tap_to_speak': 'Tippen Sie zum Sprechen',
      'listening': 'Hört zu...',
      
      // Medical History
      'medical_history': 'Krankengeschichte',
      'allergies': 'Allergien',
      'add_allergy': 'Allergie hinzufügen',
      'type_allergy': 'Allergiename eingeben',
      
      // Clinical Media
      'step_4_visual_probe': 'Schritt 4: Visuelle Sonde',
      'take_a_photo': 'Machen Sie ein Foto von jeder sichtbaren Wunde, Hautausschlag oder Erkrankung, um die KI-Bewertung zu unterstützen.',
      'no_images_captured': 'Keine Bilder erfasst',
      'camera': 'Kamera',
      'gallery': 'Galerie', 
      'clinical_media': 'Klinische Medien',
      'attach_images': 'Bilder anhängen (Röntgenbilder, Wunden usw.)',
      'add_image': 'Bild hinzufügen',
      'images_attached': 'Bild(er) angehängt',
      
      // Actions
      'submit_for_triage': 'Für KI-Triage einreichen',
      'retry': 'Wiederholen',
      'copy_text': 'Text kopieren',
      'delete_redownload_model': 'Modell löschen und erneut herunterladen',
      
      // Triage Screen
     'triage_analysis': 'Triage-Analyse',
      'analyzing_clinical_data': 'Klinische Daten werden analysiert...',
      'initializing': 'Inizialisierung...',
      'determining_category': 'KATEGORIE WIRD BESTIMMT...',
      'recommended_triage_category': 'Empfohlene Triage-Kategorie',
      'clinical_reasoning': 'Klinische Begründung',
      'initializing_triage_engine': 'Triage-Engine wird initialisiert...',
      'follow_up_clinical_questions': 'Klinische Nachfragen',
      'ask_about_case': 'Fragen Sie zu diesem Fall...',
      'you': 'Sie',
      'medical_ai': 'Medizinische KI',
      'share_pdf_report': 'PDF-Bericht teilen',
      'waking_up_ai_intelligence': 'Aufwecken der künstlichen Intelligenz...', 
      'return_to_dashboard': 'Zurück zum Dashboard',
      'failed_to_generate_pdf': 'Fehler beim Generieren des PDFs', 
      'recommended_triage_category': 'Empfohlene Triage-Kategorie',
      'clinical_reasoning': 'Klinische Begründung',
      'share_pdf_report': 'PDF-Bericht teilen',
      'follow_up_clinical_questions': 'Klinische Nachfragen',
      'ask_about_this_case': 'Fragen Sie zu diesem Fall...',
       

      // Model Download
      'downloading_medical_model': 'Medizinisches Modell wird heruntergeladen',
      'downloading_medgemma': 'MedGemma 3 Intelligence wird heruntergeladen...',
      
      // Settings
      'ai_performance': 'KI-Leistung',
      'model_intelligence': 'Modellintelligenz (maxTokens)',
      'model_intelligence_desc': 'Höhere Werte erzeugen längere, detailliertere Begründungen, verwenden aber mehr RAM.',
      'fast': 'Schnell',
      'detailed': 'Detailliert',
      'current': 'Aktuell',
      'hardware_acceleration': 'Hardware-Beschleunigung',
      'hardware_acceleration_desc': 'GPU ist schneller, kann aber auf Geräten mit weniger als 6 GB RAM abstürzen. CPU ist sicherer für 4-GB-RAM-Geräte.',
      'use_gpu_acceleration': 'GPU-Beschleunigung verwenden',
      'enabled_experimental': 'Aktiviert (Experimentell)',
      'disabled_software_mode': 'Deaktiviert (Software-Modus)',
      'optimization_tip': 'Optimierungstipp',
      'optimization_tip_text': 'Wenn die App während \'Analysieren...\' geschlossen wird, versuchen Sie, maxTokens auf 256 zu reduzieren und die GPU-Beschleunigung zu deaktivieren.',
      'model_management': 'Modellverwaltung',
      'model_management_desc': 'Verwalten Sie das multimodale medizinische Modell MedGemma 3 (4.5 Go)',
      'model_downloaded': 'Modell heruntergeladen', 
      'model_missing': 'Modell fehlt',
      'system_ready': 'System bereit für die klinische Analyse',
      'download_required': 'Download erforderlich, um die Triage zu starten',
      'download_model': 'Modell herunterladen',
      'delete_model': 'Modell löschen',
      
      // Language Settings
      'language': 'Sprache',
      'language_desc': 'Wählen Sie Ihre bevorzugte Sprache. KI-Antworten werden in dieser Sprache sein.',
      'english': 'Englisch (US)',
      'french': 'Französisch (FR)',
      'spanish': 'Spanisch (ES)',
      'italian': 'Italienisch (IT)',
      'german': 'Deutsch (DE)',
      'portuguese': 'Portugiesisch (PT)',
      
      // Errors
      'inference_error': 'Inferenzfehler',
      'error_message': 'Das KI-Modell hat einen Fehler festgestellt. Bitte kopieren Sie diese Nachricht für den Support:',
      'model_deleted_message': 'Modell gelöscht. Bitte starten Sie die Aufnahme erneut, um erneut herunterzuladen.',
      'failed_to_generate_pdf': 'PDF konnte nicht generiert werden',
      'error_copied': 'Fehler in Zwischenablage kopiert',
      
      // Time
      'waking_up_ai': 'KI-Intelligenz wird geweckt...',
      'usually_takes_time': 'Dies dauert normalerweise 10-30 Sekunden, abhängig von der Gerätegeschwindigkeit.',
      
      // History Screen
      'assessment_history': 'Bewertungsverlauf',
      'search_patients': 'Patienten suchen...',
      'no_history_found': 'Kein Verlauf gefunden',
      'delete_assessment': 'Bewertung löschen',
      'confirm_delete': 'Sind Sie sicher, dass Sie diese Bewertung löschen möchten?',
      'delete': 'Löschen',
      'cancel': 'Abbrechen',
      // Prompt construction
      'prompt_intro': 'Basierend auf den folgenden Beobachtungen zum Patienten:',
      'prompt_age': 'Alter:',
      'prompt_gender': 'Geschlecht:',
      'prompt_vitals': 'Vitalparameter:',
      'prompt_history_summary': 'Zusammenfassung der Krankengeschichte:',
      'prompt_begin_immediately': 'Beginnen Sie Ihre Antwort SOFORT mit dem Triage-Tag, dann',
      'prompt_images_analysis': 'erstellen Sie eine kurze Analyse der beigefügten klinischen Bilder und',
      'prompt_treatment_plan': 'geben Sie Ihre Differenzialdiagnose, dringende Maßnahmen und den Behandlungsplan für dieses Symptom an:',
      'prompt_tokens_limit': 'Tokens unter Verwendung dieser EXAKTEN MarkDown-Struktur:',
      'prompt_structure_triage': '[TRIAGE:RED] oder [TRIAGE:YELLOW] oder [TRIAGE:GREEN]',
      'prompt_structure_images': '## Analyse klinischer Bilder.',
      'prompt_structure_diagnosis': '## Differenzialdiagnose und dringende Maßnahmen.',
      'prompt_structure_concise_diagnosis': '### Präzise Diagnose:',
      'prompt_structure_explain_diagnoses': '(Listen Sie 2-3 mögliche Diagnosen auf und erläutern Sie diese)',
      'prompt_structure_urgent_actions': '### Zu ergreifende dringende Maßnahmen:',
      'prompt_structure_list_actions': '(Listen Sie 3-5 dringende Maßnahmen auf)',
      'prompt_structure_treatment_plan': '## Behandlungsplan:',
      'prompt_structure_list_steps': '(Listen Sie 3-5 Behandlungsschritte auf)',
      'unknown': 'Unbekannt',
      'prompt_Glucose': 'Glukose',
      'prompt_Height': 'Größe',
      'prompt_Weight': 'Gewicht',
      'prompt_Allergies': 'Allergien',
      'prompt_Question': 'Frage: Antworte immer auf',
      'prompt_in_less_than': 'in weniger als',
      'prompt_with_a_structured_markdown_response': 'mit einer strukturierten Markdown-Antwort.',
      'prompt_tokens': 'Tokens',
    },
    
    'pt_PT': {
      // App General
      'app_title': 'KintaMed Edge',
      'app_settings': 'Configurações do aplicativo',
      'return_to_dashboard': 'Voltar ao painel',
      'back_to_intake': 'Voltar à admissão',
      'Expert_care_slogan': 'Cuidado especializado, inteligência clínica, em todos os lugares.',
      // Home Screen
      'welcome': 'Bem-vindo ao',
      'tagline': 'Triagem médica alimentada por IA ao seu alcance',
      'start_assessment': 'Iniciar nova avaliação',
      'view_history': 'Ver histórico de avaliações',
      'settings': 'Configurações',
      'this_application_is_secure': 'Esta aplicação é segura. Todos os dados do paciente estão encriptados e permanecem no seu dispositivo.',
      'Privacy_Policy': 'Política de privacidade',
      'Terms_of_Service': 'Termos de serviço',
      'offline_ready_private': 'Pronto offline e privado',
      'preparing_clinical_intelligence': 'Preparação da inteligência clínica',
      'ensuring_the_latest_medical_database_is_ready': 'Garantir que a última base de dados médica esteja pronta.',
      'downloading_clinical_intelligence': 'Download da inteligência clínica',
      'fetching_the_medical_reasoning_database': 'Recuperação da base de dados de raciocínio médico.',
      'download_failed': 'Download falhado',
      'connectivity_issue_detected': 'Problema de conectividade detectado. Toque no botão abaixo para tentar novamente.',
      'retry_download': 'Tentar novamente o download',
      
      // Intake Screen
      'step_1_patient_identity': 'Passo 1: Identidade do paciente',
      'patient_intake': 'Admissão do paciente',
      'patient_information': 'Informações do paciente',
      'full_name': 'Nome completo',
      'date_of_birth': 'Data de nascimento',
      'gender': 'Gênero',
      'male': 'Masculino',
      'female': 'Feminino',
      'other': 'Outro',
      'first_name': 'Primeiro nome',
      'last_name': 'Sobrenome',
      'biological_sex': 'Sexo biológico',
      'emergency_contact_phone': 'Telefone de contato de emergência',
      'emergency_contact_name': 'Nome do contato de emergência',  
      'other': 'Outro',
      'next_step': 'Próximo passo',
      'back': 'Voltar',
      'clinical_data_collection': 'Coleta de dados clínicos',
      // Allergies
      'step_2_allergies_sensitivities': 'Passo 2: Alergias e sensibilidades',
      'please_check_all_that_apply_provide_details_if_selected': 'Por favor, marque todas as opções aplicáveis. Forneça detalhes se selecionado.',
      'medication_allergies': 'Alergias medicamentosas',
      'food_allergies': 'Alergias alimentares',
      'environmental_other': 'Alergias ambientais/outras',    
      // Vitals
      'step_3_vital_signs': 'Passo 3: Sinais vitais',
      'reason_for_consultation': 'Razão da consulta',
      'describe_the_patients_main_complaint': 'Descreva a principal queixa do paciente',
      'please_enter_a_reason': 'Por favor, insira um motivo',
      'systolic': 'Sistólica',
      'diastolic': 'Diastólica',
      'heart_rate': 'Frequência cardíaca (bpm)',
      'temperature': 'Temperatura (°C)',
      'spo2': 'SpO2 (%)',
      'glucose': 'Glicose (mg/dL)',
      'height': 'Altura (cm)',
      'weight': 'Peso (kg)',        
      // Symptoms
      'symptoms_complaints': 'Sintomas e queixas',
      'describe_symptoms': 'Descreva os sintomas em detalhes...',
      'tap_to_speak': 'Toque para falar',
      'listening': 'Ouvindo...',
      
      // Medical History
      'medical_history': 'Histórico médico',
      'allergies': 'Alergias',
      'add_allergy': 'Adicionar alergia',
      'type_allergy': 'Digite o nome da alergia',
      
      // Clinical Media
      'step_4_visual_probe': 'Passo 4: Sonde visual',
      'take_a_photo': 'Tire uma foto de qualquer ferida, erupção cutânea ou condição visível para ajudar na avaliação da IA.',
      'no_images_captured': 'Nenhuma imagem capturada',
      'camera': 'Câmera',
      'gallery': 'Galeria', 
      'clinical_media': 'Mídia clínica',
      'attach_images': 'Anexar imagens (raios-X, feridas, etc.)',
      'add_image': 'Adicionar imagem',
      'images_attached': 'imagem(ns) anexada(s)',
      
      // Actions
      'submit_for_triage': 'Enviar para triagem IA',
      'retry': 'Tentar novamente',
      'copy_text': 'Copiar texto',
      'delete_redownload_model': 'Excluir e baixar novamente o modelo',
      
      // Triage Screen
      'triage_analysis': 'Análise de triagem',
      'analyzing_clinical_data': 'Analisando dados clínicos...',
      'initializing': 'Inicializando...',
      'determining_category': 'DETERMINANDO CATEGORIA...',
      'recommended_triage_category': 'Categoria de triagem recomendada',
      'clinical_reasoning': 'Raciocínio clínico',
      'initializing_triage_engine': 'Inicializando motor de triagem...',
      'follow_up_clinical_questions': 'Perguntas clínicas de acompanhamento',
      'ask_about_case': 'Perguntar sobre este caso...',
      'you': 'Você',
      'medical_ai': 'IA médica',
      'share_pdf_report': 'Compartilhar relatório PDF',
      'waking_up_ai_intelligence': 'Despertando a inteligência artificial...',
      'return_to_dashboard': 'Voltar ao painel',
      'failed_to_generate_pdf': 'Falha ao gerar PDF',
      'recommended_triage_category': 'Categoria de triagem recomendada',
      'clinical_reasoning': 'Raciocínio clínico',
      'share_pdf_report': 'Compartilhar relatório PDF',
      'follow_up_clinical_questions': 'Perguntas clínicas de acompanhamento',
      'ask_about_this_case': 'Perguntar sobre este caso...',
      
      // Model Download
      'downloading_medical_model': 'Baixando modelo médico',
      'downloading_medgemma': 'Baixando MedGemma 3 Intelligence...',
      
      // Settings
      'ai_performance': 'Desempenho da IA',
      'model_intelligence': 'Inteligência do modelo (maxTokens)',
      'model_intelligence_desc': 'Valores mais altos produzem raciocínio mais longo e detalhado, mas usam mais RAM.',
      'fast': 'Rápido',
      'detailed': 'Detalhado',
      'current': 'Atual',
      'hardware_acceleration': 'Aceleração de hardware',
      'hardware_acceleration_desc': 'GPU é mais rápido, mas pode travar em dispositivos com menos de 6GB de RAM. CPU é mais seguro para dispositivos de 4GB de RAM.',
      'use_gpu_acceleration': 'Usar aceleração GPU',
      'enabled_experimental': 'Ativado (Experimental)',
      'disabled_software_mode': 'Desativado (Modo software)',
      'optimization_tip': 'Dica de otimização',
      'optimization_tip_text': 'Se o aplicativo fechar durante \'Analisando...\', tente reduzir maxTokens para 256 e desativar a aceleração GPU.',
      'model_management': 'Gerenciamento de modelos',
      'model_management_desc': 'Gérer le modèle multimodal médical Gemma 3 (4.5 Go)',
      'model_downloaded': 'Modèle téléchargé',
      'model_missing': 'Modèle manquant',
      'system_ready': 'Système prêt pour l\'analyse clinique',
      'download_required': 'Téléchargement requis pour commencer le triage',
      'download_model': 'Télécharger le modèle',
      'delete_model': 'Supprimer le modèle',
      
      // Language Settings
      'language': 'Idioma',
      'language_desc': 'Escolha seu idioma preferido. As respostas da IA estarão neste idioma.',
      'english': 'Inglês (US)',
      'french': 'Francês (FR)',
      'spanish': 'Espanhol (ES)',
      'italian': 'Italiano (IT)',
      'german': 'Alemão (DE)',
      'portuguese': 'Português (PT)',
      
      // Errors
      'inference_error': 'Erro de inferência',
      'error_message': 'O modelo de IA encontrou um erro. Por favor, copie esta mensagem para suporte:',
      'model_deleted_message': 'Modelo excluído. Por favor, inicie a admissão novamente para baixar novamente.',
      'failed_to_generate_pdf': 'Falha ao gerar PDF',
      'error_copied': 'Erro copiado para a área de transferência',
      
      // Time
      'waking_up_ai': 'Despertando inteligência IA...',
      'usually_takes_time': 'Isso geralmente leva 10-30 segundos, dependendo da velocidade do dispositivo.',
      
      // History Screen
      'assessment_history': 'Histórico de avaliações',
      'search_patients': 'Pesquisar pacientes...',
      'no_history_found': 'Nenhum histórico encontrado',
      'delete_assessment': 'Excluir avaliação',
      'confirm_delete': 'Tem certeza de que deseja excluir esta avaliação?',
      'delete': 'Excluir',
      'cancel': 'Cancelar',
      // Prompt construction
      'prompt_intro': 'Com base nas seguintes observações sobre o paciente:',
      'prompt_age': 'Idade:',
      'prompt_gender': 'Gênero:',
      'prompt_vitals': 'Sinais vitais:',
      'prompt_history_summary': 'Resumo do histórico médico:',
      'prompt_begin_immediately': 'Comece sua resposta IMEDIATAMENTE com a tag de triagem, depois',
      'prompt_images_analysis': 'forneça uma breve análise das imagens clínicas anexadas e',
      'prompt_treatment_plan': 'forneça seu diagnóstico diferencial, ações urgentes e plano de tratamento para este sintoma:',
      'prompt_tokens_limit': 'tokens usando esta estrutura MarkDown EXATA:',
      'prompt_structure_triage': '[TRIAGE:RED] ou [TRIAGE:YELLOW] ou [TRIAGE:GREEN]',
      'prompt_structure_images': '## Análise de imagens clínicas.',
      'prompt_structure_diagnosis': '## Diagnóstico diferencial e ações urgentes.',
      'prompt_structure_concise_diagnosis': '### Diagnóstico conciso:',
      'prompt_structure_explain_diagnoses': '(Liste e explique 2 a 3 possíveis diagnósticos)',
      'prompt_structure_urgent_actions': '### Ações urgentes a serem tomadas:',
      'prompt_structure_list_actions': '(Liste de 3 a 5 ações urgentes)',
      'prompt_structure_treatment_plan': '## Plano de tratamento:',
      'prompt_structure_list_steps': '(Liste de 3 a 5 etapas do tratamento)',
      'unknown': 'Desconhecido',
      'prompt_Glucose': 'Glicose',
      'prompt_Height': 'Altura',
      'prompt_Weight': 'Peso',
      'prompt_Allergies': 'Alergias',
      'prompt_Question': 'Pergunta: Responda sempre em',
      'prompt_in_less_than': 'em menos de',
      'prompt_with_a_structured_markdown_response': 'com uma resposta estruturada em Markdown.',
      'prompt_tokens': 'tokens',
    },
  };

  String translate(String key) {
    final languageCode = '${locale.languageCode}_${locale.countryCode}';
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en_US']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supportedLocale) =>
          supportedLocale.languageCode == locale.languageCode &&
          supportedLocale.countryCode == locale.countryCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
